nodejs:
  image: node:7.10.0-alpine
  ports:
    - ${public_port}:8888
  volumes:
    - ${volume_app}:/usr/src/app:ro
  working_dir: /usr/src/app
  command: ${commands}
  environment:
    - PORT=8080
    - HOST=localhost
    - LPC_HOST=http://localhost:8080
    - CCU_HOST=https://integration.compte.laposte.fr
    - CCU_ID=lpc
    - CCU_SECRET=lpcClientSecret
    - DISABLE_TESTS_ROUTES=false
    - SECRET_KEY_STATE=bhunjivgy
    - LOGIN_CABESTAN=WS_LAPOSTECONNECT
    - PASSWORD_CABESTAN=3z8UfMc6
    - CABESTAN_HOST=http://secure.cabestan.com
    - CABESTAN_REINIT=DS12012017163420
    - CABESTANT_FINALIZE=DS09122016093242
    - LPC_NODE_HOST=http://localhost:8080
    - LPC_HOST_SHORT=localhost:8080
    - GENERIC_REDIRECT_URL=https://recette.laposte.fr

# https://github.com/kriasoft/nodejs-api-starter/blob/master/docker-compose.yml