nodejs:
  image: node:7.10.0-alpine
  ports:
    - ${public_port}:80
  volumes:
    - ${volume_app}:/usr/src/app:ro
  working_dir: /usr/src/app
  command: ${commands}
  environment:
    - NODE_DEBUG=false
    - CORS_ORIGIN=http://localhost:3001,http://localhost:3000
    - DATABASE_URL=postgres://postgres@db:5432/dev
    - DATABASE_DEBUG=false
    - REDIS_URL=redis://redis:6379/0
    - SESSION_SECRET=wZjwhFtzQsd7r87W6AZw45Sm
    - FACEBOOK_ID=1821424564802638
    - FACEBOOK_SECRET=2339bdf25f236a42fc3a18280bf455e8
    - GOOGLE_ID=xxxxx.apps.googleusercontent.com
    - GOOGLE_SECRET=xxxxx
    - TWITTER_KEY=xxxxx
    - TWITTER_SECRET=xxxxx  

# https://github.com/kriasoft/nodejs-api-starter/blob/master/docker-compose.yml